# Generated by Django 4.1 on 2022-08-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_visit_options_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='todo',
            field=models.CharField(max_length=100),
        ),
    ]
